# Global config options accessed by AppConfig.foo
defaults: &defaults
  table_length: 5
  msg:
    place_first: Please place the robot on the table first...

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults