# Global config options accessed by AppConfig.foo
defaults: &defaults
  msg_place_first: Please place the robot on the table first...
  msg_place_args: Invalid PLACE command arguments x-position, y-position, NORTH/SOUTH/EAST/WEST
  default_height: 5
  default_width: 5

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults